# Generated by ASYNC-Chisel. 
# For more information please visit https://github.com/Jilin-Zhang/ASYNC-Chisel 

-from	GCD_main/CL_GCD/UAC_CL                   -to	GCD_main/MUX_GCD/UAC_MUX                 -through 	GCD_main/MUX_GCD/UAC_MUX/Dreq_1/Z 
-from	GCD_main/MUX_GCD/UAC_MUX                 -to	GCD_main/CL_GCD/UAC_CL                   -through 	GCD_main/CL_GCD/UAC_CL/Dreq_0/Z 
