# Generated by ASYNC-Chisel. 
# For more information please visit https://github.com/Jilin-Zhang/ASYNC-Chisel 

Async controller 0  : GCD_main/CL_GCD/UAC_CL                   
Async controller 1  : GCD_main/MUX_GCD/UAC_MUX                 
