# Generated by ASYNC-Chisel. 
# For more information please visit https://github.com/Jilin-Zhang/ASYNC-Chisel 

-from	Fibonacci_main/F_Fork/Click_Fork         -to	Fibonacci_main/F_Fork_1/Click_Fork       -through 	Fibonacci_main/F_Fork_1/Click_Fork/Dreq_0/Z 
-from	Fibonacci_main/F_Fork/Click_Fork         -to	Fibonacci_main/CL/Click_Join             -through 	Fibonacci_main/CL/Click_Join/Dreq_0/Z 
-from	Fibonacci_main/F_Fork_1/Click_Fork       -to	Fibonacci_main/CL/Click_Join             -through 	Fibonacci_main/CL/Click_Join/Dreq_1/Z 
-from	Fibonacci_main/CL/Click_Join             -to	Fibonacci_main/F_Fork/Click_Fork         -through 	Fibonacci_main/F_Fork/Click_Fork/Dreq_0/Z 
