# Generated by ASYNC-Chisel. 
# For more information please visit https://github.com/Jilin-Zhang/ASYNC-Chisel 

-from	Fork_Join/Fork/ACG                       -to	Fork_Join/Join/ACG_Join                  -through 	Fork_Join/Join/ACG_Join/Dreq_0/Z 
-from	Fork_Join/Fork/ACG                       -to	Fork_Join/Join/ACG_Join                  -through 	Fork_Join/Join/ACG_Join/Dreq_1/Z 
